const serviceText = {
  p1: "We will engage with the client to create elegant designs that are compatible with the majority of operating systems and Smart devices as a well-known provider of UI/UX designing services. We adhere to cutting-edge design standards, which enable our designers to produce visually appealing Designs.",
  p2: "We establish recognized brand identities using the most up-to-date design platforms and technologies. In addition to enhancing user experience, our UI/UX designs also increase commercial value to help you remain ahead of the always advancing competition. It might be challenging to create basic yet appealing designs, but our designers are fully capable of working their magic.",
  img: "/Mobile wireframe.svg",
};

const serviceSliders = [
  {
    title: "Food Delivery App Development:",
    text: "On-Demand Food Delivery App Development Company With fully digital synced solutions for food delivery, you can put your potential customers at ease and make ordering food online simple. Add a useful mobile app to your food delivery company to automate deliveries, better manage orders, and increase ROI.",
    img: "/foodApp.png",
  },
  {
    title: "grocery Delivery App Development:",
    text: "On-Demand Food Delivery App Development Company With fully digital synced solutions for food delivery, you can put your potential customers at ease and make ordering food online simple. Add a useful mobile app to your food delivery company to automate deliveries, better manage orders, and increase ROI.",
    img: "/foodApp.png",
  },
  {
    title: "other Delivery App Development:",
    text: "On-Demand Food Delivery App Development Company With fully digital synced solutions for food delivery, you can put your potential customers at ease and make ordering food online simple. Add a useful mobile app to your food delivery company to automate deliveries, better manage orders, and increase ROI.",
    img: "/foodApp.png",
  },
];

const caseStudyHomePage = [
  {
    bgImg: "/csbg1.png",
    portfolioImg: "/otherCSP.png",
    productLogo: "/cpLogo.png",
    productName: "Klapty",
    productDevelopmenent: "Web Develpoment",
    usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
  },
  {
    bgImg: "/csbg2.png",
    portfolioImg: "/otherCSP.png",
    productLogo: "/cpLogo.png",
    productName: "Klapty",
    productDevelopmenent: "Web Develpoment",
    usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
  },
  {
    bgImg: "/csbg3.png",
    portfolioImg: "/otherCSP.png",
    productLogo: "/cpLogo.png",
    productName: "Klapty",
    productDevelopmenent: "Web Develpoment",
    usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
  },
  {
    bgImg: "/csbg2.png",
    portfolioImg: "/otherCSP.png",
    productLogo: "/cpLogo.png",
    productName: "Klapty",
    productDevelopmenent: "Web Develpoment",
    usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
  },
  {
    bgImg: "/csbg1.png",
    portfolioImg: "/otherCSP.png",
    productLogo: "/cpLogo.png",
    productName: "Klapty",
    productDevelopmenent: "Web Develpoment",
    usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
  },
  {
    bgImg: "/csbg3.png",
    portfolioImg: "/otherCSP.png",
    productLogo: "/cpLogo.png",
    productName: "Klapty",
    productDevelopmenent: "Web Develpoment",
    usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
  },
  {
    bgImg: "/csbg1.png",
    portfolioImg: "/otherCSP.png",
    productLogo: "/cpLogo.png",
    productName: "Klapty",
    productDevelopmenent: "Web Develpoment",
    usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
  },
  {
    bgImg: "/csbg3.png",
    portfolioImg: "/otherCSP.png",
    productLogo: "/cpLogo.png",
    productName: "Klapty",
    productDevelopmenent: "Web Develpoment",
    usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
  },
  {
    bgImg: "/csbg2.png",
    portfolioImg: "/otherCSP.png",
    productLogo: "/cpLogo.png",
    productName: "Klapty",
    productDevelopmenent: "Web Develpoment",
    usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
  },
];

const caseStudy = {
  app: "android",
  cpLogo: "/cpLogo.png",
  productName: "Klapty",
  about: "Create, Share and Discover",
  technologies: [
    "/laravel logo.png",
    "/sql logo.png",
    "/angular logo.png",
    "/php logo.png",
  ],
  productImg: "/demoPc.png",
  projectOverview: [
    "Kalpty - an ultimate platform used to create and share 360° virtual tours from all around the globe. At Klapty, we are passionate about everything connected to tech and innovation. Therefore, we are aimed at shaping a modern outlook on 360 degrees virtual tours. At Klapty, They strongly believe that virtual tours are the future of the way we rent and sell real estate, select hotels for our vacation and simply spend our free time to discover the world. There is nothing easier and faster than watching a 360° tour of a property instead of arranging many meetings with the agent to first observe the house on-spot.",
    "Klapty team understands all the perks that 360 degree virtual tours bring to all of us. For this very reason, we are devoted to establishing an international platform for creating and sharing 360° tours in a matter of minutes, or, for directly hire a photographer online who specialises in virtual tours.",
  ],
  clientRequirment: [
    "You may wonder who stands behind Klapty. Let’s get to know our team a little bit closer. The Klapty team is an amazing family that work hard every day (and night) to offer you the easiest tool and the best service !",
    "Klapty’s CEO - a talented developer passionate about photography who once decided to try something new and start doing 360° tours photo shoots.",
    "Klapty’s COO – passionate about technology and Startups, who had studying Business in Switzerland and in America (Texas A&M) for master’s degree.",
  ],
  featureOfProject: [
    "Upload Unlimited Virtual Tours",
    "Upload Unlimited Virtual Tours",
    "Upload Unlimited Virtual Tours",
    "Upload Unlimited Virtual Tours",
    "Upload Unlimited Virtual Tours",
    "Upload Unlimited Virtual Tours",
    "Upload Unlimited Virtual Tours",
    "Upload Unlimited Virtual Tours",
    "Upload Unlimited Virtual Tours",
    "Upload Unlimited Virtual Tours",
  ],
  // portfolio: [portfolioPC, portfolioPC, portfolioPC, portfolioPC],
  portfolio: [
    "/android.png",
    "/android.png",
    "/android.png",
    "/android.png",
    "/android.png",
    "/android.png",
  ],
  fontFamily: "Source Sans Pro",
  colorPallete: ["#ED2323", "#F0BC11", "#F4F7F6"],
  techStack: [
    { img: "/techStackLaravel.png", tech: "Laravel" },
    { img: "/techStackPHP.png", tech: "Php" },
    { img: "/techStackSQL.png", tech: "MySQL" },
    { img: "/techStackAngular.png", tech: "Angular Js" },
  ],
  result:
    "Klapty is a rapidly growing community that already count more than 50,000 virtual tours lovers from +180 countries.",
  otherCasestudies: [
    {
      bgImg: "/csbg1.png",
      portfolioImg: "/otherCSP.png",
      productLogo: "/cpLogo.png",
      productName: "Klapty",
      productDevelopmenent: "Web Develpoment",
      usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
    },
    {
      bgImg: "/csbg2.png",
      portfolioImg: "/otherCSP.png",
      productLogo: "/cpLogo.png",
      productName: "Klapty",
      productDevelopmenent: "Web Develpoment",
      usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
    },
    {
      bgImg: "/csbg3.png",
      portfolioImg: "/otherCSP.png",
      productLogo: "/cpLogo.png",
      productName: "Klapty",
      productDevelopmenent: "Web Develpoment",
      usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
    },
    {
      bgImg: "/csbg2.png",
      portfolioImg: "/otherCSP.png",
      productLogo: "/cpLogo.png",
      productName: "Klapty",
      productDevelopmenent: "Web Develpoment",
      usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
    },
    {
      bgImg: "/csbg1.png",
      portfolioImg: "/otherCSP.png",
      productLogo: "/cpLogo.png",
      productName: "Klapty",
      productDevelopmenent: "Web Develpoment",
      usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
    },
    {
      bgImg: "/csbg3.png",
      portfolioImg: "/otherCSP.png",
      productLogo: "/cpLogo.png",
      productName: "Klapty",
      productDevelopmenent: "Web Develpoment",
      usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
    },
    {
      bgImg: "/csbg1.png",
      portfolioImg: "/otherCSP.png",
      productLogo: "/cpLogo.png",
      productName: "Klapty",
      productDevelopmenent: "Web Develpoment",
      usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
    },
    {
      bgImg: "/csbg3.png",
      portfolioImg: "/otherCSP.png",
      productLogo: "/cpLogo.png",
      productName: "Klapty",
      productDevelopmenent: "Web Develpoment",
      usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
    },
    {
      bgImg: "/csbg2.png",
      portfolioImg: "/otherCSP.png",
      productLogo: "/cpLogo.png",
      productName: "Klapty",
      productDevelopmenent: "Web Develpoment",
      usedTech: ["Laravel", "PHP", "MySql", "Angular JS"],
    },
  ],
};

export { serviceText, serviceSliders, caseStudyHomePage, caseStudy };
